name: Nikkei Alert Bot

on:
  # 手動実行もできるように
  workflow_dispatch:

  # 毎週 木曜 12:00 (UTC) → 日本時間で木曜 21:00
  schedule:
    - cron: '0 12 * * 4'

jobs:
  run-alert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 lxml

      - name: Run Nikkei Alert script
        run: |
          python nikkei_alert.py
